/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import AccesoDatos.AccesoDatos;
import Entidades.DeduccionesAumentos;
import Entidades.Nomina;
import LogicaNegocio.LogicaEmail;
import java.io.File;
import java.io.IOException;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import LogicaNegocio.LogicaDeduccionesAumentos;
import java.util.logging.Level;
import java.util.logging.Logger;
import LogicaNegocio.LogicaPatrono;
import Entidades.DeduccionesPatrono;
import com.itextpdf.text.DocumentException;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import Entidades.Empleado;
import java.util.ArrayList;
import java.util.List;

public class MantenimientoNomina extends javax.swing.JFrame {

    private final LogicaDeduccionesAumentos objLogicaDeducciones = new LogicaDeduccionesAumentos();
    LogicaPatrono objLogicaPatrono = new LogicaPatrono();
    Empleado objUsuario = new Empleado();
    AccesoDatos objAccesoDatos = new AccesoDatos();
    int xMouse, yMouse;

    public MantenimientoNomina() {
        initComponents();
        try {
            objLogicaDeducciones.cargarUsuario(tblUsuariosNomina);
        } catch (IOException ex) {
            Logger.getLogger(MantenimientoNomina.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttVolverMU = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        bttBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnenviarPatrono = new javax.swing.JButton();
        bttSumaCcssPatrono = new javax.swing.JButton();
        txfSumaCcssPatrono = new javax.swing.JTextField();
        bttSumaSalarios = new javax.swing.JButton();
        txfSumaSalarios = new javax.swing.JTextField();
        bttPdf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuariosNomina = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sg = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        bttVover = new javax.swing.JButton();
        header = new javax.swing.JPanel();

        bttVolverMU.setText("⬅");
        bttVolverMU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVolverMUActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setText("🔎");
        txtBuscar.setBorder(null);
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 193, -1));

        bttBuscar.setBackground(new java.awt.Color(255, 153, 0));
        bttBuscar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttBuscar.setForeground(new java.awt.Color(255, 255, 255));
        bttBuscar.setText("Buscar");
        bttBuscar.setBorderPainted(false);
        bttBuscar.setFocusable(false);
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar PDF a todos los Usuarios");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        btnenviarPatrono.setBackground(new java.awt.Color(255, 153, 0));
        btnenviarPatrono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnenviarPatrono.setForeground(new java.awt.Color(255, 255, 255));
        btnenviarPatrono.setText("Enviar PDF Patrono");
        btnenviarPatrono.setBorderPainted(false);
        btnenviarPatrono.setFocusable(false);
        btnenviarPatrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarPatronoActionPerformed(evt);
            }
        });
        jPanel1.add(btnenviarPatrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        bttSumaCcssPatrono.setBackground(new java.awt.Color(255, 153, 0));
        bttSumaCcssPatrono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttSumaCcssPatrono.setForeground(new java.awt.Color(255, 255, 255));
        bttSumaCcssPatrono.setText("Sumar CCSS Patrono");
        bttSumaCcssPatrono.setBorderPainted(false);
        bttSumaCcssPatrono.setFocusable(false);
        bttSumaCcssPatrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSumaCcssPatronoActionPerformed(evt);
            }
        });
        jPanel1.add(bttSumaCcssPatrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        txfSumaCcssPatrono.setEditable(false);
        txfSumaCcssPatrono.setBackground(new java.awt.Color(255, 255, 255));
        txfSumaCcssPatrono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txfSumaCcssPatrono.setBorder(null);
        txfSumaCcssPatrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSumaCcssPatronoActionPerformed(evt);
            }
        });
        jPanel1.add(txfSumaCcssPatrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 112, 20));

        bttSumaSalarios.setBackground(new java.awt.Color(255, 153, 0));
        bttSumaSalarios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttSumaSalarios.setForeground(new java.awt.Color(255, 255, 255));
        bttSumaSalarios.setText("Sumar Salarios");
        bttSumaSalarios.setBorderPainted(false);
        bttSumaSalarios.setFocusable(false);
        bttSumaSalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSumaSalariosActionPerformed(evt);
            }
        });
        jPanel1.add(bttSumaSalarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, -1, -1));

        txfSumaSalarios.setEditable(false);
        txfSumaSalarios.setBackground(new java.awt.Color(255, 255, 255));
        txfSumaSalarios.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txfSumaSalarios.setBorder(null);
        txfSumaSalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSumaSalariosActionPerformed(evt);
            }
        });
        jPanel1.add(txfSumaSalarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 530, 112, 20));

        bttPdf.setBackground(new java.awt.Color(255, 153, 0));
        bttPdf.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bttPdf.setForeground(new java.awt.Color(255, 255, 255));
        bttPdf.setText("Enviar PDF Usuario");
        bttPdf.setBorderPainted(false);
        bttPdf.setFocusable(false);
        bttPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPdfActionPerformed(evt);
            }
        });
        jPanel1.add(bttPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        tblUsuariosNomina.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblUsuariosNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuariosNomina.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblUsuariosNomina);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 71, 1420, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 550, 112, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 112, 10));

        sg.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        sg.setText("Nómina  de Empresa");
        sg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sgMouseDragged(evt);
            }
        });
        sg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sgMousePressed(evt);
            }
        });
        jPanel1.add(sg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 80));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 200, 10));

        bttVover.setBackground(new java.awt.Color(255, 153, 0));
        bttVover.setForeground(new java.awt.Color(255, 255, 255));
        bttVover.setText("⬅");
        bttVover.setBorderPainted(false);
        bttVover.setFocusable(false);
        bttVover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoverActionPerformed(evt);
            }
        });
        jPanel1.add(bttVover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 20, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1480, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttVolverMUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVolverMUActionPerformed
        dispose();
        new Opciones().setVisible(true);

    }//GEN-LAST:event_bttVolverMUActionPerformed
    private final LogicaEmail logicaEmail = new LogicaEmail();

    private void bttPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPdfActionPerformed
         int filaSeleccionada = tblUsuariosNomina.getSelectedRow();
    if (filaSeleccionada != -1) { // Verificar si hay una fila seleccionada
        // Crear un Runnable para ejecutar la tarea en un hilo separado
        Runnable tareaCorreo = new Runnable() {
            @Override
            public void run() {
                try {
                    // Obtener datos específicos de la fila seleccionada
                    String id = tblUsuariosNomina.getValueAt(filaSeleccionada, 0).toString();
                    String fechaIngreso = tblUsuariosNomina.getValueAt(filaSeleccionada, 1).toString();
                    String nombre = tblUsuariosNomina.getValueAt(filaSeleccionada, 2).toString();
                    String cedula = tblUsuariosNomina.getValueAt(filaSeleccionada, 3).toString();
                    String correo = tblUsuariosNomina.getValueAt(filaSeleccionada, 4).toString();
                    double salario = Double.parseDouble(tblUsuariosNomina.getValueAt(filaSeleccionada, 5).toString());
                    double horasRebajadas = Double.parseDouble(tblUsuariosNomina.getValueAt(filaSeleccionada, 8).toString());
                    String diasRebajados = tblUsuariosNomina.getValueAt(filaSeleccionada, 7).toString();
                    double renta = Double.parseDouble(tblUsuariosNomina.getValueAt(filaSeleccionada, 9).toString());
                    double seguro = Double.parseDouble(tblUsuariosNomina.getValueAt(filaSeleccionada, 10).toString());
                    double salarioNeto = Double.parseDouble(tblUsuariosNomina.getValueAt(filaSeleccionada, 12).toString());
                    double valorHoraOrdinaria = Double.parseDouble(tblUsuariosNomina.getValueAt(filaSeleccionada, 6).toString());

                    // Crear mensaje y archivo adjunto
                    Empleado objUsuario = new Empleado();
                    Nomina objNomina = new Nomina();
                    DeduccionesAumentos objDeducciones = new DeduccionesAumentos();
                    DeduccionesPatrono objPatrono = new DeduccionesPatrono();
                    objUsuario.setCorreo(correo);
                    objUsuario.setNombre(nombre);
                    objUsuario.setSalario(salario);
                    objDeducciones.getValorHoraOrdinaria();
                    objNomina.setDiasNoLaborados(Double.parseDouble(diasRebajados));
                    objDeducciones.setRenta(renta);
                    objDeducciones.setHorasExtra(horasRebajadas);
                    objNomina.setSalarioNeto(salarioNeto);
                    objUsuario.setFechaIngreso(fechaIngreso);
                    objUsuario.setCedula(cedula);
                    objDeducciones.setValorHoraOrdinaria(valorHoraOrdinaria);
                    objPatrono.setCcssPagarIndividual(seguro);
                    Object pdf = logicaEmail.crearPDF(objUsuario, objNomina, objDeducciones, objPatrono);

                    // Llamar al método enviarCorreo de la instancia de LogicaEmail
                    logicaEmail.enviarCorreo(correo, "Plantilla " + nombre, "Plantilla " + nombre, pdf);
                    JOptionPane.showMessageDialog(null, "Correo enviado satisfactoriamente a " + nombre);

                } catch (IOException | MessagingException ex) {
                    JOptionPane.showMessageDialog(null, "Ingrese un correo válido");
                } catch (DocumentException ex) {
                    Logger.getLogger(MantenimientoNomina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };

        // Ejecutar la tarea en un hilo separado
        Thread hiloCorreo = new Thread(tareaCorreo);
        hiloCorreo.start();
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bttPdfActionPerformed

    private void txfSumaSalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSumaSalariosActionPerformed

        txfSumaSalarios.setEditable(false);


    }//GEN-LAST:event_txfSumaSalariosActionPerformed

    private void bttSumaSalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSumaSalariosActionPerformed
        DeduccionesPatrono objPatrono = new DeduccionesPatrono();

        try {
            objPatrono.setSalariosPagar(objLogicaPatrono.SumaSalarios(objAccesoDatos));
        } catch (IOException ex) {
            Logger.getLogger(MantenimientoNomina.class.getName()).log(Level.SEVERE, null, ex);
        }

        txfSumaSalarios.setText(String.valueOf(objPatrono.getSalariosPagar()));
    }//GEN-LAST:event_bttSumaSalariosActionPerformed

    private void txfSumaCcssPatronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSumaCcssPatronoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSumaCcssPatronoActionPerformed

    private void bttSumaCcssPatronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSumaCcssPatronoActionPerformed

        DeduccionesPatrono objPatrono = new DeduccionesPatrono();
        try {

            objPatrono.setCcssPagarTotal(objLogicaPatrono.sumarValoresPosicion11(objAccesoDatos));
        } catch (IOException ex) {
            Logger.getLogger(MantenimientoNomina.class.getName()).log(Level.SEVERE, null, ex);
        }

        txfSumaCcssPatrono.setText(String.valueOf(objPatrono.getCcssPagarTotal()));
    }//GEN-LAST:event_bttSumaCcssPatronoActionPerformed
    

    private void btnenviarPatronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarPatronoActionPerformed
       // Crear un Runnable para ejecutar la tarea en un hilo separado
    Runnable tareaEnvioPatrono = new Runnable() {
        @Override
        public void run() {
            try {
                Empleado objUsuario = new Empleado();
                AccesoDatos objAccesoDatos = new AccesoDatos();
                objAccesoDatos.setNombreArchivo("usuarios.txt");
                objUsuario.setListaUsuarios(objAccesoDatos.leerArchivo(objAccesoDatos));

                ArrayList<String[]> listaUsuarios = objUsuario.getListaUsuarios(); // Aquí obtienes la lista de usuarios
                File pdfFile = logicaEmail.GenerartablaAPDF(listaUsuarios);

                String patronoEmail = "alonsomatarrita2@gmail.com"; // Reemplaza con la dirección real
                logicaEmail.enviarCorreo2(patronoEmail, "Informe Completo de Nómina", "Adjunto se encuentra el informe completo de la nómina.", pdfFile.getAbsolutePath());

                JOptionPane.showMessageDialog(null, "Correo enviado satisfactoriamente con el informe de nómina.");

                pdfFile.delete();
            } catch (IOException | DocumentException | MessagingException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    };

    // Ejecutar la tarea en un hilo separado
    Thread hiloEnvioPatrono = new Thread(tareaEnvioPatrono);
    hiloEnvioPatrono.start();
    }//GEN-LAST:event_btnenviarPatronoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // Crear un Runnable para ejecutar la tarea en un hilo separado
    Runnable tareaEnvioCorreos = new Runnable() {
        @Override
        public void run() {
            DefaultTableModel model = (DefaultTableModel) tblUsuariosNomina.getModel();
            int rowCount = model.getRowCount();

            try {
                for (int i = 0; i < rowCount; i++) {
                    // Obtener datos específicos de la fila seleccionada
                    String id = tblUsuariosNomina.getValueAt(i, 0).toString(); // Suponiendo que la columna 0 es el ID
                    String fechaIngreso = tblUsuariosNomina.getValueAt(i, 1).toString();
                    String nombre = tblUsuariosNomina.getValueAt(i, 2).toString(); // Suponiendo que la columna 1 es el Nombre
                    String cedula = tblUsuariosNomina.getValueAt(i, 3).toString(); // Suponiendo que la columna 2 es la Cédula
                    String correo = tblUsuariosNomina.getValueAt(i, 4).toString();// Suponiendo que la columna 3 es el Correo
                    double salario = Double.parseDouble(tblUsuariosNomina.getValueAt(i, 5).toString()); // Suponiendo que la columna 4 es el Salario
                    double horasRebajadas = Double.parseDouble(tblUsuariosNomina.getValueAt(i, 8).toString());// Suponiendo que la columna 5 son los dias a rebajar        
                    String diasRebajados = tblUsuariosNomina.getValueAt(i, 7).toString();// Suponiendo que la columna 5 son los dias a rebajar
                    double renta = Double.parseDouble(tblUsuariosNomina.getValueAt(i, 9).toString());// Suponiendo que la columna 6 es la renta
                    double seguro = Double.parseDouble(tblUsuariosNomina.getValueAt(i, 10).toString());// Suponiendo que la columna 7 es el seguro
                    double salarioNeto = Double.parseDouble(tblUsuariosNomina.getValueAt(i, 12).toString());// Suponiendo que la columna 8 es el salario neto
                    double valorHoraOrdinaria = Double.parseDouble(tblUsuariosNomina.getValueAt(i, 6).toString());

                    // Setear al usuario
                    Empleado objUsuario = new Empleado();
                    Nomina objNomina = new Nomina();
                    DeduccionesAumentos objDeducciones = new DeduccionesAumentos();
                    DeduccionesPatrono objPatrono = new DeduccionesPatrono();
                    objUsuario.setCorreo(correo);
                    objUsuario.setNombre(nombre);
                    objUsuario.setSalario(salario);
                    objDeducciones.getValorHoraOrdinaria();
                    objNomina.setDiasNoLaborados(Double.parseDouble(diasRebajados));
                    objDeducciones.setRenta(renta);
                    objDeducciones.setHorasExtra(horasRebajadas);
                    objNomina.setSalarioNeto(salarioNeto);
                    objUsuario.setFechaIngreso(fechaIngreso);
                    objUsuario.setCedula(cedula);
                    objDeducciones.setValorHoraOrdinaria(valorHoraOrdinaria);
                    objPatrono.setCcssPagarIndividual(seguro);
                    Object pdf = logicaEmail.crearPDF(objUsuario, objNomina, objDeducciones, objPatrono);

                    // Llamar al método enviarCorreo de la instancia de LogicaEmail
                    logicaEmail.enviarCorreo(correo, "Plantilla " + nombre, "Plantilla " + nombre, pdf);
                    
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al enviar el correo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (MessagingException | DocumentException ex) {
                Logger.getLogger(MantenimientoNomina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };
    
    

    // Ejecutar la tarea en un hilo separado
    Thread hiloEnvioCorreos = new Thread(tareaEnvioCorreos);
    hiloEnvioCorreos.start();
    JOptionPane.showMessageDialog(null, "Todos los correos han sido enviados satisfactoriamente " );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarYResaltar() {

        String textoBusqueda = txtBuscar.getText().toLowerCase();
        tblUsuariosNomina.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(tblUsuariosNomina, value, isSelected, hasFocus, row, column);
                String nombre = tblUsuariosNomina.getValueAt(row, 2).toString().toLowerCase(); // Asumiendo que la columna de nombre es la 0
                if (textoBusqueda.length() > 0 && nombre.contains(textoBusqueda)) {
                    c.setBackground(Color.BLUE);
                    c.setForeground(Color.WHITE);
                } else {
                    c.setBackground(Color.WHITE);
                    c.setForeground(Color.BLACK);
                }
                return c;
            }
        });
        tblUsuariosNomina.repaint();
    }
    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed

        buscarYResaltar(); // Llamada al método buscarYResaltar cuando se presiona el botón


    }//GEN-LAST:event_bttBuscarActionPerformed

    private void sgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_sgMouseDragged

    private void sgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sgMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgMousePressed

    private void bttVoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoverActionPerformed
        dispose();
        new Opciones().setVisible(true);
    }//GEN-LAST:event_bttVoverActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
         if (txtBuscar.getText().equals("🔎")) {
            txtBuscar.setText("");
            txtBuscar.setForeground(Color.black);

        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        if (txtBuscar.getText().isEmpty()) {
           txtBuscar.setText("🔎");
            txtBuscar.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviarPatrono;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttPdf;
    private javax.swing.JButton bttSumaCcssPatrono;
    private javax.swing.JButton bttSumaSalarios;
    private javax.swing.JButton bttVolverMU;
    private javax.swing.JButton bttVover;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel sg;
    private javax.swing.JTable tblUsuariosNomina;
    private javax.swing.JTextField txfSumaCcssPatrono;
    private javax.swing.JTextField txfSumaSalarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
