/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import LogicaNegocio.LogicaUsuario;
import LogicaNegocio.LogicaEmpleado;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author beto
 */
public class Opciones extends javax.swing.JFrame {

    private final LogicaEmpleado objLogicaUsuario = new LogicaEmpleado();
    private final LogicaUsuario objLogicaAdmin = new LogicaUsuario();
    int xMouse, yMouse;

    public Opciones() {
        initComponents();
    }

    private void abrirMantenimientoUsuario() {
        try {
            MantenimientoEmpleado mantenimientoUsuarioFrame = new MantenimientoEmpleado();
            mantenimientoUsuarioFrame.setVisible(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al abrir la ventana Mantenimiento de Usuarios: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirMantenimientoAdmin() {
        try {
            MantenimientoAdmin mantenimientoAdminFrame = new MantenimientoAdmin();
            mantenimientoAdminFrame.setVisible(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al abrir la ventana Mantenimiento de Administradores: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bttRegistrar = new javax.swing.JButton();
        bttNomina = new javax.swing.JButton();
        btnagregaradmin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        bttCerrar.setText("Cerrar");
        bttCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setFocusable(false);
        exitBtn.setPreferredSize(new java.awt.Dimension(40, 40));

        exitTxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setToolTipText("");
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.setVerifyInputWhenFocusTarget(false);
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 23)); // NOI18N
        jLabel1.setText("Menú de Opciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        bttRegistrar.setBackground(new java.awt.Color(255, 153, 0));
        bttRegistrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        bttRegistrar.setText("Registrar Usuarios");
        bttRegistrar.setBorderPainted(false);
        bttRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttRegistrar.setFocusable(false);
        bttRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(bttRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 220, 46));

        bttNomina.setBackground(new java.awt.Color(255, 153, 0));
        bttNomina.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttNomina.setForeground(new java.awt.Color(255, 255, 255));
        bttNomina.setText("Nómina Usuarios");
        bttNomina.setBorderPainted(false);
        bttNomina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttNomina.setFocusable(false);
        bttNomina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNominaActionPerformed(evt);
            }
        });
        jPanel1.add(bttNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 199, 45));

        btnagregaradmin.setBackground(new java.awt.Color(255, 153, 0));
        btnagregaradmin.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnagregaradmin.setForeground(new java.awt.Color(255, 255, 255));
        btnagregaradmin.setText("Agregar Admin");
        btnagregaradmin.setBorderPainted(false);
        btnagregaradmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregaradmin.setFocusable(false);
        btnagregaradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregaradminActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregaradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 200, 45));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 259, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 259, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 259, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarActionPerformed

        System.exit(WIDTH);
    }//GEN-LAST:event_bttCerrarActionPerformed

    private void btnagregaradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregaradminActionPerformed
        if (objLogicaAdmin.VerificarArchivo()) {
            abrirMantenimientoAdmin();
        } else {
            int opcion = JOptionPane.showConfirmDialog(this,
                "El archivo Admin.txt no existe. ¿Desea crearlo?",
                "Crear archivo",
                JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                try {
                    objLogicaAdmin.CrearArchivo();
                    JOptionPane.showMessageDialog(this,
                        "Archivo Admin.txt creado correctamente.",
                        "Archivo creado",
                        JOptionPane.INFORMATION_MESSAGE);

                    // Abrir la ventana MantenimientoNomina después de crear el archivo
                    abrirMantenimientoAdmin();

                } catch (IOException ex) {
                    Logger.getLogger(Opciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        dispose();
    }//GEN-LAST:event_btnagregaradminActionPerformed

    private void bttNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNominaActionPerformed
        abrirMantenimientoNomina();
        dispose();
        }

        private void abrirMantenimientoNomina() {
            MantenimientoNomina mantenimientoNominaFrame = new MantenimientoNomina();
            mantenimientoNominaFrame.setVisible(true);
    }//GEN-LAST:event_bttNominaActionPerformed

    private void bttRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegistrarActionPerformed

        if (objLogicaUsuario.VerificarArchivo()) {
            abrirMantenimientoUsuario();
        } else {
            int opcion = JOptionPane.showConfirmDialog(this,
                "El archivo usuarios.txt no existe. ¿Desea crearlo?",
                "Crear archivo",
                JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                try {
                    objLogicaUsuario.CrearArchivo();
                    JOptionPane.showMessageDialog(this,
                        "Archivo usuarios.txt creado correctamente.",
                        "Archivo creado",
                        JOptionPane.INFORMATION_MESSAGE);

                    // Abrir la ventana MantenimientoNomina después de crear el archivo
                    abrirMantenimientoUsuario();

                } catch (IOException ex) {
                    Logger.getLogger(Opciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        dispose();

    }//GEN-LAST:event_bttRegistrarActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitTxtMousePressed

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregaradmin;
    private javax.swing.JButton bttCerrar;
    private javax.swing.JButton bttNomina;
    private javax.swing.JButton bttRegistrar;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
